pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 10, unit: 'MINUTES') // Set a timeout for the pipeline
        disableConcurrentBuilds()       // Prevent parallel executions
        timestamps()                 // Enable timestamps in logs
    }
    stages {
        stage('Build') {
            steps {
                echo "Building the application..."
            }

        }
        stage('test') {
            steps {
                echo "testing the application..."
            }

        }
        stage('deploy') {
            steps {
                echo "deploying the application..."
            }

        }
    }
    post {
        always {
            echo "this section always runs" // echo command here is groovy , not shell scripting 
            deleteDir()                     // delete workspace directory after building 
        }
        success {
            echo " this section runs only when pipeline is success"
        }
        failure {
            echo "this section runs only when pipeline is failure"
        }

    }
    
}
// deletedir() works only inside a node {} block or a script {} block when used in post {} in declarative pipelines. Since you are using a declarative pipeline, deletedir() needs to be wrapped in script {} inside post {}.

